# ===== SERVICE =====
spring.application.name=CoursServices
server.port=8082

# ===== MYSQL DATASOURCE =====
spring.datasource.url=jdbc:mysql://localhost:3306/cours_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== RABBITMQ (Communication ASYNCHRONE avec EXAMEN) =====
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===== EUREKA (Découverte des services) =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

# ===== LOGGING =====
logging.level.tn.esprit.spring.cours=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG