spring.application.name=ConfigServer

server.port=8889

welcome.message=hello from config server

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

#config server
#charger les fichiers de configuration localement dans le projet existe dans le config
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=classpath:/config