# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/ApiGateway-0.0.1-SNAPSHOT.jar  ApiGateway.jar


# Expose the port your application runs on
EXPOSE 8956

# Run the JAR file
ENTRYPOINT ["java","-jar","ApiGateway.jar"] 