spring.application.name=ApiGateway2
server.port=8956


eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka


# ===============================
# ENABLE SPRING CLOUD CONFIG
# ===============================
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8889

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/EduRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/EduRealm/protocol/openid-connect/certs

# Expose actuator health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# DISABLE DEFAULT CORS
# ===============================
spring.webflux.cors.enabled=false

# ===============================
# CLOUD GATEWAY - DISABLE GLOBAL CORS
# ===============================
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=false

