# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:17-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/MicroServiceProject-0.0.1-SNAPSHOT.jar Microservice.jar


# Expose the port your application runs on
EXPOSE 8083

# Run the JAR file
ENTRYPOINT ["java","-jar","Microservice.jar"] 