# Use Node.js runtime
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY dist/ ./dist/
COPY package*.json ./

# Install dependencies
RUN npm install


# Build NestJS (TypeScript -> dist)
RUN npm run build

# Expose port (par défaut NestJS = 3000)
EXPOSE 3000

# Run the app
ENTRYPOINT ["node", "dist/main.js"]